# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a128d99eb0c9bac8cd3aef6c61e976fadaa63ae522131e23c886e89217ae3d03d49aac62d87b75d1609fcf6010f6e2454a68e7d36b12f095433ad8cba707280

test:
  secret_key_base: b7264aefbfac67b6180cd38ac26b2859a537d6686018ef7b2f6cc17854b226e2279e49f278891498feebe4084a63e690e4c77ea68417f94bce9c7b8a33abb581

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
